---
title: Tubodin Industrial Ltda.
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  produtos:
    title: Produtos
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: produtos
  values:
    layout: produto
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: 'Atuamos no setor de sistemas hidráulicos desde 1989, com certificação
  ISO 9001:2008 desde Maio de 2005. Oferecemos uma gama diversificada de conexões,
  mangueiras  hidráulicas, terminais e abraçadeiras para fixação de tubos. Entre em
  contato com nosso departamento de vendas.

'
endereco:
- Rua Rio de Janeiro, 381
- Jardim Casa Grande
- Diadema - SP - Cep. 09981-730
telefone:
  label: "(11) 4053-8500"
  number: 551140538500
facebook_name: "/tubodin"
twitter_name: "/tubodin"
email: vendas@tubodin.com.br
baseurl: 
url: http://tubodin.com.br
markdown: kramdown
permalink: pretty/
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
catalogos:
- nome: Mangueiras e Terminais para Tubos Flagelados
  file: 
